###
# Copyright (C) 2020 Temuri Takalandze <me@abgeo.dev>
#
# This material can not be copied and/or
# distributed without the express permission of Temuri Takalandze.
#
# Written by Temuri Takalandze <me@abgeo.dev>, November 2020
###

version: "3.8"
services:
  php:
    image: php:8.0-rc-cli
    container_name: php
    working_dir: /var/app
    volumes:
      - ./code:/var/app
    command: sh -c 'tail -f /dev/null'
